engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
        - javascript

ratings:
  paths:
    - "**.js"
    - "**.jsx"
  exclude_paths:
    - node_modules/**/*
