sudo: required
dist: trusty

language:
  - node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - NODE_ENV=test npm run db:migrate

script:
  - npm test

after_success:
  - npm run coveralls